#!/usr/bin/awk -f

BEGIN {
    N = 0
    X = 0
    Y = 0
    XY = 0
    X2 = 0
    rx = "([0-9]+(\\.[0-9]+)?)";
    perfect_rx = "^"rx"$";
}

$1 ~ perfect_rx && $2 ~ perfect_rx {
    add($1, $2);
}

$1 ~ /\d+/ && $2 = /\d+/ {
    match($1, rx, results);
    Xi = results[1];
    match($2, rx, results);
    Yi = results[1];
    add(Xi, Yi);
}

function add(Xi, Yi) {
    N += 1;
    X += Xi;
    Y += Yi;
    XY += Xi * Yi;
    X2 += Xi * Xi;
}
 
 END {
    slope = (N * XY - X*Y) / (N*X2 - X*X)
    b = (Y - slope * X) / N
    printf("%.3fX + %.3f\n", slope, b);
}
